/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#cfc4c5",
        "inverse-surface": "#2e3132",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "primary-fixed-dim": "#c6c6c6",
        "inverse-on-surface": "#f0f1f2",
        "surface-dim": "#d9dadb",
        "primary-container": "#1b1b1b",
        "surface-container-highest": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-primary-fixed-variant": "#474747",
        "on-secondary-fixed-variant": "#2f2ebe",
        "inverse-primary": "#c6c6c6",
        "secondary-fixed": "#e1e0ff",
        "surface-container-high": "#e7e8e9",
        primary: "#000000",
        "secondary-fixed-dim": "#c0c1ff",
        "on-secondary": "#ffffff",
        "tertiary-container": "#2c0051",
        "surface-tint": "#5e5e5e",
        "on-primary-container": "#848484",
        "on-tertiary-fixed": "#2c0051",
        "primary-fixed": "#e2e2e2",
        secondary: "#4648d4",
        "surface-container": "#edeeef",
        "surface-bright": "#f8f9fa",
        "on-error": "#ffffff",
        "on-primary-fixed": "#1b1b1b",
        "tertiary-fixed": "#f0dbff",
        "surface-container-low": "#f3f4f5",
        tertiary: "#000000",
        "on-surface-variant": "#4c4546",
        "on-secondary-container": "#fffbff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#6900b3",
        "error-container": "#ffdad6",
        outline: "#7e7576",
        "on-secondary-fixed": "#07006c",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e1e3e4",
        "on-tertiary-container": "#ac59fb",
        "tertiary-fixed-dim": "#ddb7ff",
        "on-background": "#191c1d",
        "secondary-container": "#6063ee",
        "surface-container-lowest": "#ffffff",
        background: "#f8f9fa",
        surface: "#f8f9fa",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-gap": "160px",
        "container-max": "1280px",
        "margin-mobile": "24px",
        "stack-md": "16px",
        gutter: "32px",
        "section-gap-mobile": "80px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "margin-desktop": "64px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-xl": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-lg-mobile": [
          "48px",
          {
            lineHeight: "52px",
            letterSpacing: "-0.02em",
            fontWeight: "800",
          },
        ],
        "label-caps": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.1em",
            fontWeight: "500",
          },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": [
          "84px",
          {
            lineHeight: "92px",
            letterSpacing: "-0.04em",
            fontWeight: "800",
          },
        ],
      },
    },
  },
  plugins: [],
};
